all:
	pdflatex mtsxivslsh
	#latex mtsxivslsh
	bibtex mtsxivslsh
	#latex mtsxivslsh
	#latex mtsxivslsh
	pdflatex mtsxivslsh
	pdflatex mtsxivslsh
clean:
	rm mtsxivslsh.aux mtsxivslsh.pdf mtsxivslsh.blg mtsxivslsh.bbl mtsxivslsh.log
