all:
	pdflatex apertium-hbs-slv
	bibtex apertium-hbs-slv
	pdflatex apertium-hbs-slv
	pdflatex apertium-hbs-slv
clean:
	rm apertium-hbs-slv.aux apertium-hbs-slv.pdf apertium-hbs-slv.blg apertium-hbs-slv.bbl apertium-hbs-slv.log apertium-hbs-slv.ps apertium-hbs-slv.dvi
